# Generated by Django 5.2.4 on 2025-07-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_estimate_days',
            field=models.PositiveIntegerField(default=3, help_text='Estimate in days from order date'),
        ),
    ]
